core/blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from . import views

app_name = "blog"

urlpatterns = [
    path("fbv-index/", views.indexView, name='fbv-index'),
    path("cbv-index/", TemplateView.as_view(template_name='index.html', extra_context={"name": "class base view"}), name='cbv-index'),
    path("cbv-index-custum/", views.IndexTemplateView.as_view(), name='cbv-index-custum'),
    path('go-to-itmeter/', RedirectView.as_view(url='https://itmeter.ir/'), name='go-to-itmeter'),
    path('go-to-index-cbv/', RedirectView.as_view(pattern_name="blog:cbv-index"), name='go-to-cbv-index'),
    
    # custum redirect 
    path('go-to-itmeter-fbv/', views.redirectFBV, name='redirect-fbv'),
    path('go-to-itmeter-cbv/', views.RedirectCBV.as_view(), name='redirect-cbv'),
    
    path('post/', views.PostListView.as_view(), name="post-list"),
    path('post/api/', views.PostListAPIView.as_view(), name="post-list-api"),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/create-by-formview/', views.PostCreateFormView.as_view(), name='post-create-by-formview'),
    path('post/create-by-creatview/', views.PostCreateView.as_view(), name='post-create-by-creatview'),
    path('post/<int:pk>/edit/', views.PostEditView.as_view(), name='post-edit'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    
    # 5
    path('post-httpresponse/', views.post_list_view, name='httpresponse-post-list'),
    # path('post-api-view/', views.api_post_list_view, name='api-post-list'),
    
    path('api/v1/', include('blog.api.v1.urls')),
    
    path('', views.Indexview.as_view(), name='index'),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Task API",
        default_version="v1",
        description="The description of ToDo CBV project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="poorya189@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),

    # path("accounts/", include("accounts.urls")),
    path("blog/", include("blog.urls")),

    path('api-auth/', include('rest_framework.urls')),

    path("swagger/output.json", schema_view.without_ui(cache_timeout=0), name="schema-json",),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui",),

]



if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]

# serving static and medi for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/templates/base.html
{% load static %}
{% load custom_filters %}
{% load template_tag %}
<!-- load compress -->
<!DOCTYPE html>
<html lang="en">

<!-- Basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Mobile Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1 , shrink-to-fit=no , user-scalable=no">
<!--<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->

<!-- Site Metas -->
<title>itmeter - Breaking News in a Digital World!</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="">

<!-- Site Icons -->
<link rel="shortcut icon" href="{% static 'images/it-logo.png' %}" type="image/x-icon" />
<link rel="apple-touch-icon" href="{% static 'images/it-logo.png' %}">

<!-- Design fonts -->
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- compress css -->
<!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

<!-- FontAwesome Icons core CSS -->
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

<!-- Custom CSS styles for this template -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<!-- Responsive styles for this template -->
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">

<!-- Colors for this template -->
<link href="{% static 'css/colors.css' %}" rel="stylesheet">

<!-- Version Tech CSS for this template -->
<link href="{% static 'css/version/tech.css' %}" rel="stylesheet">
 <!-- endcompress %} -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">
        <header class="tech-header header">
            <div class="container-fluid">
                <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
                     <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'homepage:index' %}"><img style="width:200px;height:50px;" src="{% static 'images/version/tech-logo-.png' %}" alt=""></a>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                            </li>
                            <!--<li class="nav-item">
                                <a class="nav-link" href="category-02.html">Videos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="category-03.html">Reviews</a>
                            </li>-->
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'homepage:contact' %}">Contact Us</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav mr-2">
                            {% if request.user.is_authenticated %}
                            <li class="nav-item nav-link">Logged in as {{request.user.username}}</li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
                            {% else %}

                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:rss' %}"><i class="fa fa-rss"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-android"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-apple"></i></a>
                            </li>
                        </ul>
                    </div>
                </nav>

            </div><!-- end container-fluid -->
        </header><!-- end market-header -->

        {% block content %}

        {% endblock %}

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="widget">
                            <div class="footer-text text-left">
                                <a href="{% url 'homepage:index' %}"><img style="width:200px;height:50px;" src="{% static 'images/version/tech-logo-.png' %}"
                                        alt="" class="img-fluid"></a>
                                <p>Tech Blog is a technology blog, we sharing marketing, news and gadget articles.</p>
                                <div class="social">
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i
                                            class="fa fa-facebook"></i></a>
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i
                                            class="fa fa-twitter"></i></a>
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i
                                            class="fa fa-instagram"></i></a>
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i
                                            class="fa fa-google-plus"></i></a>
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i
                                            class="fa fa-pinterest"></i></a>
                                </div>

                                <hr class="invis">

                                <div class="newsletter-widget text-left">
                                    <form class="form-inline" method="post" action="{% url 'homepage:newsletter' %}">
                                        {% csrf_token %}
                                        <input name="email" type="email" class="form-control" placeholder="Enter your email address">
                                        <button type="submit" class="btn btn-primary">SUBMIT</button>
                                    </form>
                                </div><!-- end newsletter -->
                            </div><!-- end footer-text -->
                        </div><!-- end widget -->
                    </div><!-- end col -->

                    
                    {% if '/blog' in request.path  %}
                        {% postcategories %}
                    {% else  %}
                        {% newscategories %}
                    {% endif %}
                

                    <div class="col-lg-2 col-md-12 col-sm-12 col-xs-12">
                        <div class="widget">
                            <h2 class="widget-title">Copyrights</h2>
                            <div class="link-widget">
                                <ul>
                                    <li><a href="#">About us</a></li>
                                    <li><a href="#">Advertising</a></li>
                                    <li><a href="#">Write for us</a></li>
                                    <li><a href="#">Trademark</a></li>
                                    <li><a href="#">License & Help</a></li>
                                </ul>
                            </div><!-- end link-widget -->
                        </div><!-- end widget -->
                    </div><!-- end col -->
                </div>

                <div class="row">
                    <div class="col-md-12 text-center">
                        <br>
                        <div class="copyright">&copy; Tech Blog. Design: <a href="http://html.design">HTML Design</a>.
                        </div>
                    </div>
                </div>
            </div><!-- end container -->
        </footer><!-- end footer -->        

        <div class="dmtop" style="overflow: hidden;">Scroll to Top</div>

    </div><!-- end wrapper -->
    {% if messages %}
			{% for message in messages %}
			  <div class="popup__inner">
				<div class="popup message_popup">
				  <a class="close_popup">x</a>
				  <p>{{ message }}</p>
				</div>
			  </div>
			{% endfor %}
		  {% endif %}
		  
		  
    <!--   <script>
			$(document).ready(function(){
			  $('.popup__inner').addClass('active');
			});
		  
			$(document).on('click', '.close_popup', function(e){
			  e.preventDefault();
			  $(this).closest('.popup__inner').removeClass('active');
			});
		  </script> -->
		 
		  
	<!-- <style>
			.popup__inner {
			  display: none; 
			  position: absolute;
			  top: 0;
			  left: 0;
			  width: 100%;
			  height: 500px;
			  background: rgba(0, 0, 0, 0.5);
			  justify-content: center;
			  align-items: center;
			}
			
			.popup {
			  background: white;
			  padding: 20px;
			  border-radius: 5px;
			  position: relative;
			}
		  
			.popup__inner.active {
			  display: grid;
			}
			.popup p{
				font-size: 25px;
				margin-top: 30px;
				font-weight: 600;
			  }
		  
			a.close_popup {
			  font-size: 20px;  
			  cursor: pointer;
			  position: absolute;
				top: 10px;
				right: 10px; 
				width: 30px;
				height: 30px;
				border-radius: 50% ;
				border: solid;
				border-width: 1px;
				color: black;
				background-color: #dcdcdc; 
				display: flex; 
				justify-content: center; 
				align-items: center; 
						}
		  </style> -->

    <!-- Core JavaScript
================================================== -->
    <!-- compress js -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/custom3.js' %}"></script>
     <!-- endcompress %}-->

</body>

</html>

core/templates/coming_soon-.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coming soon</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }
        h1 {
            font-size: 36px;
            color: #333;
        }
    </style>
</head>
<body>
    <h1>Will be avaliable soon...</h1>
</body>
</html>

core/templates/coming_soon.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coming soon...</title>
    <style>
        body, html {margin: 0; padding: 0; height: 100%; overflow: hidden; }
        .full-page-image {
            background-image: url("{% static 'images/comingsoon.jpg' %}");
            background-size: cover; background-position: center; height: 100%; width: 100%; }
    </style>
</head>
<body>
    <div class="full-page-image"></div>
</body>
</html>

core/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    
</body>
</html>

core/templates/tag-cloud-widget.html
{% load static %}

<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in post.tags.all %}
        <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
        {% endfor %}
    </ul>
</div>	