core/blog/api/v1/urls.py
from django.urls import path, include

from . import views

app_name = "api-v1"

urlpatterns = [
    # path('post/', views.api_post_list, name='api-post-list'),
    # path('post/<int:id>/', views.api_post_detail, name='api-post-detail'),
    
    # path('post-apiview/', views.PostListAPIView.as_view(), name='api-post-list-apiview'),
    # path('post-apiview/<int:id>/', views.PostDetailAPIView.as_view(), name='api-post-detail-apiview'),
    
    # path('post-generics/', views.PostListGenericAPIView.as_view(), name='api-post-list-generics'),
    # path('post-generics-mixins/', views.PostListGenericAPIViewMixins.as_view(), name='api-post-list-generics-mixins'),
    # path('post-generics-listcreateapiview/', views.PostListGenericsListCreateAPIView.as_view(), name='api-post-list-listcreateapiview'),
    # path('post-generics/<int:pk>/', views.PostDetailGenericAPIView.as_view(), name='api-post-detail-generics'),
    # path('post-generics-allfunction/<int:pk>/', views.PostDetailGenericRetrieveUpdateDestroyAPIView.as_view(), name='api-post-detail-generics-allfunction'),

    # path('post-viewset/', views.PostViewSet.as_view({'get':'list', 'post':'create'}), name='post-viewset'),
    # path('post-viewset/<int:pk>/', views.PostViewSet.as_view({'get':'retrieve', 'put':'update', 'patch':'partial_update', 'delete':'destroy'}), name='post-viewset'),
    # path('', include(router.urls))    

]

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
'''ViewSet
router.register('post', views.PostViewSet, basename='post')
urlpatterns = router.urls # All urls created automatically
'''

'''ModelViewSet'''
router.register('post', views.PostModelViewSet, basename='post')
router.register('category', views.CategoryModelViewSet, basename='category')
urlpatterns = router.urls # All urls created automatically

core/blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from . import views

app_name = "blog"

urlpatterns = [
    path("fbv-index/", views.indexView, name='fbv-index'),
    path("cbv-index/", TemplateView.as_view(template_name='index.html', extra_context={"name": "class base view"}), name='cbv-index'),
    path("cbv-index-custum/", views.IndexTemplateView.as_view(), name='cbv-index-custum'),
    path('go-to-itmeter/', RedirectView.as_view(url='https://itmeter.ir/'), name='go-to-itmeter'),
    path('go-to-index-cbv/', RedirectView.as_view(pattern_name="blog:cbv-index"), name='go-to-cbv-index'),
    
    # custum redirect 
    path('go-to-itmeter-fbv/', views.redirectFBV, name='redirect-fbv'),
    path('go-to-itmeter-cbv/', views.RedirectCBV.as_view(), name='redirect-cbv'),
    
    path('post/', views.PostListView.as_view(), name="post-list"),
    path('post/api/', views.PostListAPIView.as_view(), name="post-list-api"),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/create-by-formview/', views.PostCreateFormView.as_view(), name='post-create-by-formview'),
    path('post/create-by-creatview/', views.PostCreateView.as_view(), name='post-create-by-creatview'),
    path('post/<int:pk>/edit/', views.PostEditView.as_view(), name='post-edit'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    
    # 5
    path('post-httpresponse/', views.post_list_view, name='httpresponse-post-list'),
    # path('post-api-view/', views.api_post_list_view, name='api-post-list'),
    
    path('api/v1/', include('blog.api.v1.urls')),
    
    path('', views.Indexview.as_view(), name='index'),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Task API",
        default_version="v1",
        description="The description of ToDo CBV project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="poorya189@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),

    # path("accounts/", include("accounts.urls")),
    path("blog/", include("blog.urls")),

    path('api-auth/', include('rest_framework.urls')),

    path("swagger/output.json", schema_view.without_ui(cache_timeout=0), name="schema-json",),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui",),

]



if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]

# serving static and medi for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/templates/home/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<!--start education section-->
<!-- section -->
<div class="innerpage_banner">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>My Resume</h2>
            </div>
        </div>
    </div>
</div>
<!-- end section -->

<div class="section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="full center">
                    <div class="heading_main text_align_center">
                        <h2><span class="theme_color">Academic </span>Background</h2>
                        <p class="large">in Computer Engineering</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- section -->
<div class="section layout_padding theme_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 text_align_center">
                <div class="full">
                    <img class="img-responsive" src="{% static 'images/5052628.jpg' %}" alt="#" />
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 white_fonts">
                <h3 class="small_heading">Bachelor's degree in Computer Engineering</h3>
                <br><br>
                <p>I hold a Bachelor's degree in Computer Engineering, which I completed in 2021 from Shomal University.
                    My academic performance was commendable, as I graduated with an impressive GPA of 18.67. Throughout
                    my studies, I developed a strong foundation in various areas of computer science and engineering. I
                    am passionate about technology and eager to apply my knowledge in real-world applications. My
                    education has equipped me with the skills necessary to excel in the field of computer engineering.
                    
                </p><br>
                <!-- <a href="#" class="hvr-radial-out button-theme">Skills</a> -->
            </div>
        </div>
    </div>
</div>
<!-- end section -->

 
<!-- section -->
<div class="section layout_padding">
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-6">
                <div class="center">
                    <img class="responsive-img" src="{% static 'images/multilingual.png' %}" alt="#" />
                </div>
                <div class="center">
                    <h4>Language Proficiency</h4>
                </div>
            </div>

            <div class="col-lg-10 offset-lg-1 margin-top_30 gray-fonts">
                <div class="full text_align_center">
                    <p>I am proficient in English at a B2 level and achieved a score of 6.0 in the IELTS exam in 2024.
                        Additionally, I received admission to the University of Messina in Italy for a Data Science
                        program, where I participated in online classes for one semester. During this time, I also
                        learned Italian and reached an A2 level of proficiency. This experience not only enhanced my
                        language skills but also deepened my understanding of data science concepts. I am excited to
                        continue my studies and improve my language abilities further.</p>
                </div>
            </div>

        </div>
    </div>
</div>
<style>.responsive-img {width: 35% !important;
    height: auto !important;}</style>
<!-- end section -->

<!-- section -->
<div class="section layout_padding theme_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 text_align_center">
                <div class="full">
                    <img class="img-responsive" id="about-project-pic" src="{% static 'images/project.png' %}" alt="#" />
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 white_fonts">
                <h3 class="small_heading">Bachelor's Project:</h3>
                <h4>Online service - buying and selling used CARS</h4>
                <p>During my Bachelor's degree, I learned Python and developed a comprehensive online car marketplace
                    for my final project using PHP, HTML, CSS, JavaScript, and SQL Server. The website features both an
                    admin panel and a user interface for submitting vehicle sale requests. I implemented various
                    functionalities to enhance user experience and streamline the buying and selling process. After
                    completing the project, I received a perfect score of 20 out of 20. This experience not only
                    strengthened my programming skills but also deepened my understanding of web development and
                    database management.</p>
                <!-- <a href="#" class="hvr-radial-out button-theme">Education</a> -->
            </div>
        </div>
    </div>
</div>
<!-- end section -->



<!-- section -->
<div class="section layout_padding">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <div class="full center margin-bottom_30">
                    <div class="heading_main text_align_center">
                        <h2><span class="theme_color">Certificates</span> of Maktabkhooneh</h2>
                        <p class="large">Resume</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div id="demo" class="carousel slide" data-ride="carousel">
                    <!-- The slideshow -->
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <div class="row">
                                <div class="col-lg-3 col-md-6 col-sm-12">
                                    <img class="img-responsive" src="{% static 'images/Python.png' %}" alt="#"
                                        onclick="openModal(this.src, 'Python Programming')" />
                                </div>
                                <div class="col-lg-3 col-md-6 col-sm-12">
                                    <img class="img-responsive" src="{% static 'images/Advanced-Python.png' %}" alt="#"
                                        onclick="openModal(this.src)" />
                                </div>
                                <div class="col-lg-3 col-md-6 col-sm-12">
                                    <img class="img-responsive" src="{% static 'images/Django.png' %}" alt="#"
                                        onclick="openModal(this.src)" />
                                </div>
                                <div class="col-lg-3 col-md-6 col-sm-12">
                                    <img class="img-responsive" src="{% static 'images/Git.png' %}" alt="#"
                                        onclick="openModal(this.src)" />
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="row">
                                <div class="col-lg-3 col-md-6 col-sm-12">
                                    <img class="img-responsive" src="{% static 'images/OOP-Python.png' %}" alt="#"
                                        onclick="openModal(this.src)" />
                                </div>
                                <div class="col-lg-3 col-md-6 col-sm-12">
                                    <img class="img-responsive" src="{% static 'images/Machine-Learning.png' %}" alt="#"
                                        onclick="openModal(this.src)" />
                                </div>
                                <div class="col-lg-3 col-md-6 col-sm-12">
                                    <img class="img-responsive" src="{% static 'images/Advanced-Python.png' %}" alt="#"
                                        onclick="openModal(this.src)" />
                                </div>
                                <div class="col-lg-3 col-md-6 col-sm-12">
                                    <img class="img-responsive" src="{% static 'images/Git.png' %}" alt="#"
                                        onclick="openModal(this.src)" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <script>
                        function openModal(imageSrc) {
                            document.getElementById('modalImage').src = imageSrc;
                            $('#imageModal').modal('show');
                        }</script>
                    <style>
                        .modal-body {
                            display: flex;
                            justify-content: center;
                            align-items: center; 
                            padding: 0;
                        }
                        #imageModal img {
                            max-width: 140%;
                            height: auto;
                        }

                        .modal-content {
                            background-color: transparent !important;
                        }
                    </style>

                    <!-- Modal -->
                    <div class="modal fade" id="imageModal" tabindex="-1" role="dialog"
                        aria-labelledby="imageModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <img id="modalImage" class="img-fluid" src="" alt="#">
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Left and right controls -->
                    <a class="carousel-control-prev" href="#demo" data-slide="prev">
                        <span class="carousel-control-prev-icon"></span>
                    </a>
                    <a class="carousel-control-next" href="#demo" data-slide="next">
                        <span class="carousel-control-next-icon"></span>
                    </a>

                </div>
            </div>

            <div class="col-lg-12 gray-fonts">
                <p>I have completed five courses on the Maktabkhooneh website, which are: Python,
                    Advanced Python, Object-Oriented Programming in Python, Git, and Machine Learning. Currently, I am
                    enrolled in four additional courses, including Django, Advanced Django, Docker, and SQL Server
                    Database. Each of these courses has provided me with valuable knowledge and skills in programming
                    and software development. I have gained a solid foundation in Python and its advanced concepts.
                    Additionally, I am excited to learn about web development with Django and containerization with
                    Docker. I believe these skills will significantly enhance my capabilities as a developer.</p>
            </div>

            <div class="col-lg-12">
                <div class="full center">
                    <!--  <a href="#" class="hvr-radial-out button-theme">Education</a> -->
                </div>
            </div>

        </div>

    </div>
</div>
<!-- end section -->

<!--end education section-->




{% endblock %}

core/templates/home/banner-1200-1200.html
{% load static %}

<div class="widget">
    <div class="banner-spot clearfix">
        <div class="banner-img">
            <img src="{% static 'images/banner-1200-1200.jpg' %}" alt="" class="img-fluid">
        </div><!-- end banner-img -->
    </div><!-- end banner -->
</div><!-- end widget -->

core/templates/home/banner-300-600.html
{% load static %}

<div class="widget">
    <div class="banner-spot clearfix">
        <div class="banner-img">
            <img src="{% static 'images/banner-300-600.jpg' %}" alt="" class="img-fluid">
        </div><!-- end banner-img -->
    </div><!-- end banner -->
</div><!-- end widget -->

core/templates/home/categories.html
{% load static %}

<div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
    <div class="widget">
        <h2 class="widget-title">Popular Categories</h2>
        <div class="link-widget">
            <ul> 
                {% if Pcategories  %}
                    {% for cat in Pcategories|slice:"5" %}
                        <li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}} <span>{{cat.count}}</span></a></li>
                    {% endfor %}
                {% elif Ncategories  %}
                    {% for cat in Ncategories|slice:"5" %}
                        <li><a href="{% url 'homepage:category' cat_name=cat.name %}">{{cat.name}} <span>{{cat.count}}</span></a></li>
                    {% endfor %}
                {% endif %}
            </ul>
        </div><!-- end link-widget -->
    </div><!-- end widget -->
</div><!-- end col -->

core/templates/home/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-title lb single-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <h2><i class="fa fa-envelope-open-o bg-orange"></i> Contact us <small
                        class="hidden-xs-down hidden-sm-down">Nulla felis eros, varius sit amet volutpat non. </small>
                </h2>
            </div><!-- end col -->
            <div class="col-lg-4 col-md-4 col-sm-12 hidden-xs-down hidden-sm-down">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Contact</li>
                </ol>
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end page-title -->

<section class="section wb">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="row">
                        <div class="col-lg-5">
                            <h4>Who are we?</h4>
                            <p>We are a team of technology lovers who work hard to provide you with the latest news,
                                reviews, and information from the tech world. Our aim is to keep you updated and
                                interested in the constantly changing world of technology.</p>

                            <h4>How do we help?</h4>
                            <p>We assist by gathering and summarizing the newest technology news and offering detailed
                                reviews of various products and services. Our platform gives users the chance to share
                                their opinions and experiences, creating a community of tech enthusiasts who can learn
                                from one another.</p>

                            <h4>How can you get involved?</h4>
                            <p>Join us by signing up and sharing your thoughts in comments and reviews. Your opinions
                                are important to us, and we invite you to take part in our conversations to help others
                                make smart choices in technology.</p>
                        </div>
                        <div class="col-lg-7">
                            <form class="form-wrapper" method="post" action="{% url 'homepage:contact' %}">
                                {% csrf_token %}
                                <input name="name" type="text" class="form-control" placeholder="Your name">
                                <input name="email" type="emil" class="form-control" placeholder="Email address">
                                <input name="subject" type="text" class="form-control" placeholder="Subject">
                                <textarea name="message" class="form-control" placeholder="Your message"></textarea>
                                <div class="pb-3">{{form.captcha}} </div>
                                <button type="submit" class="btn btn-primary">Send <i class="fa fa-envelope-open-o"></i></button>
                            </form>
                        </div>
                    </div>
                </div><!-- end page-wrapper -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>

{% endblock %}

core/templates/home/header-news.html
{% load static %}
{% if news|length > 2 %}
<section class="section first-section">
    <div class="container-fluid">
        <div class="masonry-blog clearfix">
            {% for n in news %}
                {% if forloop.counter == 1 %}
                    <div class="first-slot d-none d-md-block">
                        <div class="masonry-box post-media">
                            <img src="{{ n.image.url }}" alt="" class="img-fluid">
                            <div class="shadoweffect">
                                <div class="shadow-desc">
                                    <div class="blog-meta">
                                      <!--<span class="bg-orange"><a href="blog.html" title="">{{n.topic}}</a></span>-->
                                        <h4><a href="{% url 'homepage:news' news_id=n.id %}" title="">{{n.title}}</a></h4>
                                        <small><a href="{% url 'homepage:news' news_id=n.id %}" title="">{{n.published_date|date:"d D m Y"}}</a></small>
                                        <small><a href="author.html" title="">{{n.author}}</a></small>
                                    </div><!-- end meta -->
                                </div><!-- end shadow-desc -->
                            </div><!-- end shadow -->
                        </div><!-- end post-media -->
                    </div><!-- end first-side -->
                {% endif %} 
                {% if forloop.counter == 2 or forloop.counter == 3 %}
                    <div class="second-slot">
                        <div class="masonry-box post-media">
                            <img src="{{ n.image.url }}" alt="" class="img-fluid">
                            <div class="shadoweffect">
                                <div class="shadow-desc">
                                    <div class="blog-meta">
                                    <!--<span class="bg-orange"><a href="blog.html" title="">{{n.topic}}</a></span>-->
                                        <h4><a href="{% url 'homepage:news' news_id=n.id %}" title="">{{n.title}}</a></h4>
                                        <small><a href="{% url 'homepage:news' news_id=n.id %}" title="">{{n.published_date|date:"d D m Y"}}</a></small>
                                        <small><a href="author.html" title="">{{n.author}}</a></small>
                                    </div><!-- end meta -->
                                </div><!-- end shadow-desc -->
                            </div><!-- end shadow -->
                        </div><!-- end post-media -->
                    </div><!-- end second-side -->
                {% endif %} 
            {% endfor %}
        </div><!-- end masonry -->
    </div>
</section>
{% endif %}

core/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% load template_tag %}
{% block content %}

{% include 'home/header-news.html' %}

<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                <div class="page-wrapper">
                    <div class="blog-top clearfix">
                        <h4 class="pull-left">Recent News <a href="#"><i class="fa fa-rss"></i></a></h4>
                    </div><!-- end blog-top -->
                    <div class="blog-list clearfix">
                        {% for n in news %}
                            <div class="blog-box row">
                                <div class="col-md-4">
                                    <div class="post-media">
                                        <a href="{% url 'homepage:news' news_id=n.id %}" title="">
                                            <img src="{{ n.image.url }}" alt="" class="img-fluid">
                                            <div class="hovereffect"></div>
                                        </a>
                                    </div><!-- end media -->
                                </div><!-- end col -->
                                <div class="blog-meta big-meta col-md-8">
                                    <h4><a href="{% url 'homepage:news' news_id=n.id %}" title="">{{n.title}}</a></h4>
                                    <p>{{n.content|truncate_w:100|safe}}</p>
                                    <small class="firstsmall"><a class="bg-orange" href="#" title="">{{n.topic}}</a></small>
                                    <small><a href="{% url 'homepage:news' news_id=n.id %}" title="">{{n.published_date|date:"d D m Y"}}</a></small>
                                    <small><a href="{% url 'homepage:author' author=n.author %}" target="_blank" title="">{{n.author}}</a></small>
                                    <small><a href="{{n.source}}" target="_blank" title="">Source</a></small>
                                    <small><a href="{% url 'homepage:news' news_id=n.id %}" title=""><i class="fa fa-eye"></i> {{n.counted_views}} Views</a></small>
                                </div><!-- end meta -->
                            </div><!-- end blog-box -->
                            <hr class="invis">
                        {% endfor %}
                    </div><!-- end blog-list -->
                </div><!-- end page-wrapper -->
                <hr class="invis">
                
                </div>
                {% include 'home/news-pagination.html' %}
            </div><!-- end col -->

            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                <div class="sidebar">
                        {% include 'home/banner-300-600.html' %}
                        <!-- home/trend-videos.html -->
                        {% include 'home/news-search.html' %}
                        {% include 'home/popular-news.html' %}
                        <!-- home/recent-reviews.html -->
                        <!-- blog/follow-us.html -->
                        {% include 'home/banner-1200-1200.html' %}                    
                </div><!-- end sidebar -->
            </div><!-- end col-lg-3 -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>
{% endblock %}

core/templates/home/news-pagination.html
{% load static %}

<div class="row">
    <div class="col-md-12">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-start">
                {% if news.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ news.previous_page_number }}" class="page-link" aria-label="Previous">
                            <span aria-hidden="true">
                                <span class="lnr lnr-chevron-left"></span>
                            </span>
                        Prev</a>
                    </li>
                {% endif %}

                {% for i in news.paginator.page_range %}
                    {% if news.number == i %}																			
                        <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                    {% else %}
                        <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                    {% endif %}
                {% endfor %}		                            
                    
                {% if news.has_next %}
                    <li class="page-item">
                        <a href="?page={{ news.next_page_number }}" class="page-link" aria-label="Next">
                            <span aria-hidden="true">
                                <span class="lnr lnr-chevron-right"></span>
                            </span>
                        Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div><!-- end col -->
</div><!-- end row -->

core/templates/home/news-search.html
{% load static %}
{% load template_tag %}
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'homepage:search' %}" method="get">
        <input placeholder="Search" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

core/templates/home/popular-news.html
{% load static %}
{% load template_tag %}
{% load humanize %} 

<div class="widget">
    <h2 class="widget-title">Most Viewed News</h2>
    <div class="blog-list-widget">
        <div class="list-group">
            {% for n in news %}
                <a href="{% url 'homepage:news' news_id=n.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="w-100 justify-content-between">
                        <img src="{{ n.image.url }}" alt="" class="img-fluid float-left">
                        <h5 class="mb-1">{{n.title|truncate_w:6|safe}}</h5>
                        <small style="margin-left:70px">{{n.published_date| naturaltime}}</small>
                    </div>
                </a>
            {% endfor %}            
        </div>
    </div><!-- end blog-list -->
</div><!-- end widget -->